"""add import job to products

Revision ID: d885a236909b
Revises: 619ae8fddd63
Create Date: 2026-08-09 12:16:08.528109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd885a236909b'
down_revision: Union[str, Sequence[str], None] = '619ae8fddd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('import_job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_import_job_id'), 'products', ['import_job_id'], unique=False)
    op.create_foreign_key(None, 'products', 'import_jobs', ['import_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_import_job_id'), table_name='products')
    op.drop_column('products', 'import_job_id')
    # ### end Alembic commands ###
